// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qesyiatchcghvqzqtgzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlc3lpYXRjaGNnaHZxenF0Z3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODIxNjgsImV4cCI6MjA2MDU1ODE2OH0.FKXFy9O724fsTxWrhVu1i75D5v8EzOL5jlONNq6QJCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);