// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bizeubjoglqagnmnttie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpemV1YmpvZ2xxYWdubW50dGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzU0MzAsImV4cCI6MjA1OTk1MTQzMH0.2Q_CFSelTqlXrofaiMYUKzOIvmqaW_NTPun2hIPE9l4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);